apiVersion: v1
data:
  config.yaml: |
    branch-protection:
      orgs: {}
      protect-tested-repos: true
    deck:
      spyglass: {}
    gerrit: {}
    owners_dir_blacklist:
      default: null
      repos: null
    plank: {}
    pod_namespace: jx
    postsubmits: {}
    presubmits: {}
    prowjob_namespace: jx
    push_gateway: {}
    sinker: {}
    tide:
      context_options:
        from-branch-protection: true
        required-if-present-contexts: null
        skip-unknown-contexts: false
      merge_method:
      queries:
      - labels:
        - approved
        missingLabels:
        - do-not-merge
        - do-not-merge/hold
        - do-not-merge/work-in-progress
        - needs-ok-to-test
        - needs-rebase
        repos:
        - rawlingsj/jx
kind: ConfigMap
metadata:
  name: config
  namespace: jx